# This first line selects our base image from Balena repository
FROM balenalib/%%BALENA_MACHINE_NAME%%:latest

# Here we install we install DDClient for dynu DNS with built-in script that makes all the update, install and cleaning for us
RUN apt-get update && apt-get install -y ddclient

COPY start.sh /usr/src/

CMD [ "/bin/bash", "/usr/src/start.sh" ]
